[package]
name = "insights"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Knowledge management and insight storage system"

[lib]
name = "insights"
path = "src/lib.rs"

[[bin]]
name = "insights"
path = "src/main.rs"

[[bin]]
name = "insights_embedding_daemon"
path = "src/bin/insights_embedding_daemon.rs"

[dependencies]
clap.workspace = true
dirs.workspace = true
chrono.workspace = true
anyhow.workspace = true
thiserror.workspace = true
colored.workspace = true
console.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
bentley.workspace = true

serde_yaml = "0.9"

# Async runtime for daemon IPC
tokio = { version = "1.47", features = ["full"] }
uuid = { version = "1.18", features = ["v4"] }

# Neural embeddings via ONNX (v2 API!)
ort = { version = "2.0.0-rc.10", features = ["fetch-models"] }
ndarray = { version = "0.16" }
tokenizers = { version = "0.21", default-features = false, features = ["onig"] }

# Candle embeddings (alternative to ONNX)
candle-core = { git = "https://github.com/huggingface/candle.git" }
candle-nn = { git = "https://github.com/huggingface/candle.git" }
candle-transformers = { git = "https://github.com/huggingface/candle.git" }
hf-hub = { version = "0.4", features = ["tokio"] }
safetensors = "0.6"

# Future: Neural embeddings when ecosystem stabilizes

[dev-dependencies]
assert_cmd = "2.0"
assert_fs = "1.1"
predicates = "3.1"
serial_test = "3.2"
tempfile.workspace = true 
