[tarpaulin]
coverage-reports = ["Html", "Json"]
output-dir = "coverage/"

fail-under = 40.0
ignore-panics = true

skip-clean = true
count = true
branch = true
forward = true

exclude-files = [
  # File-level excludes
  "*/tests/*",
  "*/examples/*",
  "*/target/*",

  # Entrypoints and CLI routers are very simple and typically aren't useful to test
  "*/cli.rs",
  "*/main.rs",

  # Oops, all system dependencies!
  # This is a setup script for NVIDIA's cuda ecosystem. It's 95% apt installs, path checking, and user-facing instructions.
  # It's not worth the effort to try to mock or do integration tests on.
  "*/install_insights_cuda_dependencies.rs",
]

timeout = "120s"

release = false

engine = "Llvm"
out = ["Html", "Json"]
print = "branch"
