[tarpaulin]
coverage-reports = ["Html", "Json"]
output-dir = "coverage/"

fail-under = 40.0
ignore-panics = true

skip-clean = true
count = true
branch = true
forward = true

exclude-files = [
  # File-level excludes
  "*/tests/*",
  "*/examples/*",
  "*/target/*",

  # Auth module uses external credentials - hard to test
  "*/auth.rs",

  # Entrypoints and CLI routers are very simple and typically aren't useful to test
  "*/cli.rs",
  "*/main.rs",
]

timeout = "120s"

release = false

engine = "Llvm"
out = ["Html", "Json"]
print = "branch"
