name: mac-os

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-macos:
    name: Test (macOS)
    runs-on: macos-14
    if: "!contains(github.event.head_commit.message, '[validated]') && !contains(github.event.head_commit.body, '[validated]')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Kernelle Dependencies
        uses: ./.github/actions/setup-kernelle

      - name: Test
        uses: ./.github/actions/test
