name: code-quality

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  code-quality:
    name: Lint, Format & Quality Analysis
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[validated]') && !contains(github.event.head_commit.body, '[validated]')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Blizz Dependencies
        uses: ./.github/actions/setup-kernelle
        with:
          rust-components: rustfmt,clippy

      - name: Check Tidiness
        run: kernelle do check-tidy
