name: test-install-cleanup

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test-install-cleanup:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[validated]') && !contains(github.event.head_commit.body, '[validated]')"
    strategy:
      matrix:
        shell: [bash, zsh]
        include:
          - shell: bash
            shell_setup: ""
          - shell: zsh
            shell_setup: "sudo apt-get update && sudo apt-get install -y zsh"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        
    - name: Setup shell
      if: matrix.shell_setup != ''
      run: ${{ matrix.shell_setup }}
      
    - name: Test Basic Install & Cleanup
      run: .github/test/install-uninstall-cycle.sh

  test-edge-cases:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        
    - name: Test install when already installed
      run: .github/test/install-when-already-installed.sh

    - name: Test uninstall when not installed
      run: .github/test/uninstall-when-not-installed.sh
